---
- name: Create frontend directory
  file:
    path: "{{ project_root }}/frontend"
    state: directory
    mode: '0755'

- name: Copy Frontend files (excluding node_modules)
  shell: |
    rsync -av --exclude='node_modules' --exclude='.git' "{{ playbook_dir }}/../frontend/" "{{ project_root }}/frontend/"
