---
- name: Create backend directory
  file:
    path: "{{ project_root }}/backend"
    state: directory
    mode: '0755'

- name: Copy Backend files
  copy:
    src: "{{ playbook_dir }}/backend/"
    dest: "{{ project_root }}/backend/"
    mode: '0755'
