apiVersion: v1
kind: Secret
metadata:
  name: study-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://kavyauppin:0711@study-tracker.0rt4b59.mongodb.net/?appName=study-tracker
  JWT_SECRET: mySuperSecretKeyForStudyTracker2024
